FROM golang:1.24-bookworm AS builder

WORKDIR /build
COPY go.mod go.sum ./
RUN go mod download

COPY . .
RUN CGO_ENABLED=0 go build -o controller ./cmd/controller/

FROM gcr.io/distroless/static-debian12:nonroot
COPY --from=builder /build/controller /controller
ENTRYPOINT ["/controller"]
