// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.35.0
// source: proto/forkd.proto

package forkdpb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ForkDaemon_CreateTemplate_FullMethodName = "/forkd.ForkDaemon/CreateTemplate"
	ForkDaemon_DeleteTemplate_FullMethodName = "/forkd.ForkDaemon/DeleteTemplate"
	ForkDaemon_ListTemplates_FullMethodName  = "/forkd.ForkDaemon/ListTemplates"
	ForkDaemon_CreateSnapshot_FullMethodName = "/forkd.ForkDaemon/CreateSnapshot"
	ForkDaemon_DeleteSnapshot_FullMethodName = "/forkd.ForkDaemon/DeleteSnapshot"
	ForkDaemon_Fork_FullMethodName           = "/forkd.ForkDaemon/Fork"
	ForkDaemon_ForkRunning_FullMethodName    = "/forkd.ForkDaemon/ForkRunning"
	ForkDaemon_Exec_FullMethodName           = "/forkd.ForkDaemon/Exec"
	ForkDaemon_ExecStream_FullMethodName     = "/forkd.ForkDaemon/ExecStream"
	ForkDaemon_Terminate_FullMethodName      = "/forkd.ForkDaemon/Terminate"
	ForkDaemon_ReadFile_FullMethodName       = "/forkd.ForkDaemon/ReadFile"
	ForkDaemon_WriteFile_FullMethodName      = "/forkd.ForkDaemon/WriteFile"
	ForkDaemon_ListDir_FullMethodName        = "/forkd.ForkDaemon/ListDir"
	ForkDaemon_GetCapacity_FullMethodName    = "/forkd.ForkDaemon/GetCapacity"
)

// ForkDaemonClient is the client API for ForkDaemon service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ForkDaemonClient interface {
	// Template management
	CreateTemplate(ctx context.Context, in *CreateTemplateRequest, opts ...grpc.CallOption) (*CreateTemplateResponse, error)
	DeleteTemplate(ctx context.Context, in *DeleteTemplateRequest, opts ...grpc.CallOption) (*DeleteTemplateResponse, error)
	ListTemplates(ctx context.Context, in *ListTemplatesRequest, opts ...grpc.CallOption) (*ListTemplatesResponse, error)
	// Snapshot management
	CreateSnapshot(ctx context.Context, in *CreateSnapshotRequest, opts ...grpc.CallOption) (*CreateSnapshotResponse, error)
	DeleteSnapshot(ctx context.Context, in *DeleteSnapshotRequest, opts ...grpc.CallOption) (*DeleteSnapshotResponse, error)
	// Fork operations (hot path — must be <2ms)
	Fork(ctx context.Context, in *ForkRequest, opts ...grpc.CallOption) (*ForkResponse, error)
	ForkRunning(ctx context.Context, in *ForkRunningRequest, opts ...grpc.CallOption) (*ForkRunningResponse, error)
	// Sandbox lifecycle
	Exec(ctx context.Context, in *ExecRequest, opts ...grpc.CallOption) (*ExecResponse, error)
	ExecStream(ctx context.Context, in *ExecStreamRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ExecStreamResponse], error)
	Terminate(ctx context.Context, in *TerminateRequest, opts ...grpc.CallOption) (*TerminateResponse, error)
	// File operations
	ReadFile(ctx context.Context, in *ReadFileRequest, opts ...grpc.CallOption) (*ReadFileResponse, error)
	WriteFile(ctx context.Context, in *WriteFileRequest, opts ...grpc.CallOption) (*WriteFileResponse, error)
	ListDir(ctx context.Context, in *ListDirRequest, opts ...grpc.CallOption) (*ListDirResponse, error)
	// Node capacity
	GetCapacity(ctx context.Context, in *GetCapacityRequest, opts ...grpc.CallOption) (*GetCapacityResponse, error)
}

type forkDaemonClient struct {
	cc grpc.ClientConnInterface
}

func NewForkDaemonClient(cc grpc.ClientConnInterface) ForkDaemonClient {
	return &forkDaemonClient{cc}
}

func (c *forkDaemonClient) CreateTemplate(ctx context.Context, in *CreateTemplateRequest, opts ...grpc.CallOption) (*CreateTemplateResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateTemplateResponse)
	err := c.cc.Invoke(ctx, ForkDaemon_CreateTemplate_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *forkDaemonClient) DeleteTemplate(ctx context.Context, in *DeleteTemplateRequest, opts ...grpc.CallOption) (*DeleteTemplateResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteTemplateResponse)
	err := c.cc.Invoke(ctx, ForkDaemon_DeleteTemplate_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *forkDaemonClient) ListTemplates(ctx context.Context, in *ListTemplatesRequest, opts ...grpc.CallOption) (*ListTemplatesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListTemplatesResponse)
	err := c.cc.Invoke(ctx, ForkDaemon_ListTemplates_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *forkDaemonClient) CreateSnapshot(ctx context.Context, in *CreateSnapshotRequest, opts ...grpc.CallOption) (*CreateSnapshotResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateSnapshotResponse)
	err := c.cc.Invoke(ctx, ForkDaemon_CreateSnapshot_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *forkDaemonClient) DeleteSnapshot(ctx context.Context, in *DeleteSnapshotRequest, opts ...grpc.CallOption) (*DeleteSnapshotResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteSnapshotResponse)
	err := c.cc.Invoke(ctx, ForkDaemon_DeleteSnapshot_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *forkDaemonClient) Fork(ctx context.Context, in *ForkRequest, opts ...grpc.CallOption) (*ForkResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ForkResponse)
	err := c.cc.Invoke(ctx, ForkDaemon_Fork_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *forkDaemonClient) ForkRunning(ctx context.Context, in *ForkRunningRequest, opts ...grpc.CallOption) (*ForkRunningResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ForkRunningResponse)
	err := c.cc.Invoke(ctx, ForkDaemon_ForkRunning_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *forkDaemonClient) Exec(ctx context.Context, in *ExecRequest, opts ...grpc.CallOption) (*ExecResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ExecResponse)
	err := c.cc.Invoke(ctx, ForkDaemon_Exec_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *forkDaemonClient) ExecStream(ctx context.Context, in *ExecStreamRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ExecStreamResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &ForkDaemon_ServiceDesc.Streams[0], ForkDaemon_ExecStream_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[ExecStreamRequest, ExecStreamResponse]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ForkDaemon_ExecStreamClient = grpc.ServerStreamingClient[ExecStreamResponse]

func (c *forkDaemonClient) Terminate(ctx context.Context, in *TerminateRequest, opts ...grpc.CallOption) (*TerminateResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TerminateResponse)
	err := c.cc.Invoke(ctx, ForkDaemon_Terminate_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *forkDaemonClient) ReadFile(ctx context.Context, in *ReadFileRequest, opts ...grpc.CallOption) (*ReadFileResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ReadFileResponse)
	err := c.cc.Invoke(ctx, ForkDaemon_ReadFile_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *forkDaemonClient) WriteFile(ctx context.Context, in *WriteFileRequest, opts ...grpc.CallOption) (*WriteFileResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(WriteFileResponse)
	err := c.cc.Invoke(ctx, ForkDaemon_WriteFile_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *forkDaemonClient) ListDir(ctx context.Context, in *ListDirRequest, opts ...grpc.CallOption) (*ListDirResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListDirResponse)
	err := c.cc.Invoke(ctx, ForkDaemon_ListDir_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *forkDaemonClient) GetCapacity(ctx context.Context, in *GetCapacityRequest, opts ...grpc.CallOption) (*GetCapacityResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetCapacityResponse)
	err := c.cc.Invoke(ctx, ForkDaemon_GetCapacity_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ForkDaemonServer is the server API for ForkDaemon service.
// All implementations must embed UnimplementedForkDaemonServer
// for forward compatibility.
type ForkDaemonServer interface {
	// Template management
	CreateTemplate(context.Context, *CreateTemplateRequest) (*CreateTemplateResponse, error)
	DeleteTemplate(context.Context, *DeleteTemplateRequest) (*DeleteTemplateResponse, error)
	ListTemplates(context.Context, *ListTemplatesRequest) (*ListTemplatesResponse, error)
	// Snapshot management
	CreateSnapshot(context.Context, *CreateSnapshotRequest) (*CreateSnapshotResponse, error)
	DeleteSnapshot(context.Context, *DeleteSnapshotRequest) (*DeleteSnapshotResponse, error)
	// Fork operations (hot path — must be <2ms)
	Fork(context.Context, *ForkRequest) (*ForkResponse, error)
	ForkRunning(context.Context, *ForkRunningRequest) (*ForkRunningResponse, error)
	// Sandbox lifecycle
	Exec(context.Context, *ExecRequest) (*ExecResponse, error)
	ExecStream(*ExecStreamRequest, grpc.ServerStreamingServer[ExecStreamResponse]) error
	Terminate(context.Context, *TerminateRequest) (*TerminateResponse, error)
	// File operations
	ReadFile(context.Context, *ReadFileRequest) (*ReadFileResponse, error)
	WriteFile(context.Context, *WriteFileRequest) (*WriteFileResponse, error)
	ListDir(context.Context, *ListDirRequest) (*ListDirResponse, error)
	// Node capacity
	GetCapacity(context.Context, *GetCapacityRequest) (*GetCapacityResponse, error)
	mustEmbedUnimplementedForkDaemonServer()
}

// UnimplementedForkDaemonServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedForkDaemonServer struct{}

func (UnimplementedForkDaemonServer) CreateTemplate(context.Context, *CreateTemplateRequest) (*CreateTemplateResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateTemplate not implemented")
}
func (UnimplementedForkDaemonServer) DeleteTemplate(context.Context, *DeleteTemplateRequest) (*DeleteTemplateResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteTemplate not implemented")
}
func (UnimplementedForkDaemonServer) ListTemplates(context.Context, *ListTemplatesRequest) (*ListTemplatesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListTemplates not implemented")
}
func (UnimplementedForkDaemonServer) CreateSnapshot(context.Context, *CreateSnapshotRequest) (*CreateSnapshotResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateSnapshot not implemented")
}
func (UnimplementedForkDaemonServer) DeleteSnapshot(context.Context, *DeleteSnapshotRequest) (*DeleteSnapshotResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteSnapshot not implemented")
}
func (UnimplementedForkDaemonServer) Fork(context.Context, *ForkRequest) (*ForkResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Fork not implemented")
}
func (UnimplementedForkDaemonServer) ForkRunning(context.Context, *ForkRunningRequest) (*ForkRunningResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ForkRunning not implemented")
}
func (UnimplementedForkDaemonServer) Exec(context.Context, *ExecRequest) (*ExecResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Exec not implemented")
}
func (UnimplementedForkDaemonServer) ExecStream(*ExecStreamRequest, grpc.ServerStreamingServer[ExecStreamResponse]) error {
	return status.Error(codes.Unimplemented, "method ExecStream not implemented")
}
func (UnimplementedForkDaemonServer) Terminate(context.Context, *TerminateRequest) (*TerminateResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Terminate not implemented")
}
func (UnimplementedForkDaemonServer) ReadFile(context.Context, *ReadFileRequest) (*ReadFileResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ReadFile not implemented")
}
func (UnimplementedForkDaemonServer) WriteFile(context.Context, *WriteFileRequest) (*WriteFileResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method WriteFile not implemented")
}
func (UnimplementedForkDaemonServer) ListDir(context.Context, *ListDirRequest) (*ListDirResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListDir not implemented")
}
func (UnimplementedForkDaemonServer) GetCapacity(context.Context, *GetCapacityRequest) (*GetCapacityResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetCapacity not implemented")
}
func (UnimplementedForkDaemonServer) mustEmbedUnimplementedForkDaemonServer() {}
func (UnimplementedForkDaemonServer) testEmbeddedByValue()                    {}

// UnsafeForkDaemonServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ForkDaemonServer will
// result in compilation errors.
type UnsafeForkDaemonServer interface {
	mustEmbedUnimplementedForkDaemonServer()
}

func RegisterForkDaemonServer(s grpc.ServiceRegistrar, srv ForkDaemonServer) {
	// If the following call panics, it indicates UnimplementedForkDaemonServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ForkDaemon_ServiceDesc, srv)
}

func _ForkDaemon_CreateTemplate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateTemplateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ForkDaemonServer).CreateTemplate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ForkDaemon_CreateTemplate_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ForkDaemonServer).CreateTemplate(ctx, req.(*CreateTemplateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ForkDaemon_DeleteTemplate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteTemplateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ForkDaemonServer).DeleteTemplate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ForkDaemon_DeleteTemplate_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ForkDaemonServer).DeleteTemplate(ctx, req.(*DeleteTemplateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ForkDaemon_ListTemplates_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListTemplatesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ForkDaemonServer).ListTemplates(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ForkDaemon_ListTemplates_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ForkDaemonServer).ListTemplates(ctx, req.(*ListTemplatesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ForkDaemon_CreateSnapshot_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateSnapshotRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ForkDaemonServer).CreateSnapshot(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ForkDaemon_CreateSnapshot_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ForkDaemonServer).CreateSnapshot(ctx, req.(*CreateSnapshotRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ForkDaemon_DeleteSnapshot_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteSnapshotRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ForkDaemonServer).DeleteSnapshot(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ForkDaemon_DeleteSnapshot_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ForkDaemonServer).DeleteSnapshot(ctx, req.(*DeleteSnapshotRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ForkDaemon_Fork_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ForkRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ForkDaemonServer).Fork(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ForkDaemon_Fork_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ForkDaemonServer).Fork(ctx, req.(*ForkRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ForkDaemon_ForkRunning_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ForkRunningRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ForkDaemonServer).ForkRunning(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ForkDaemon_ForkRunning_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ForkDaemonServer).ForkRunning(ctx, req.(*ForkRunningRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ForkDaemon_Exec_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ExecRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ForkDaemonServer).Exec(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ForkDaemon_Exec_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ForkDaemonServer).Exec(ctx, req.(*ExecRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ForkDaemon_ExecStream_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ExecStreamRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(ForkDaemonServer).ExecStream(m, &grpc.GenericServerStream[ExecStreamRequest, ExecStreamResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ForkDaemon_ExecStreamServer = grpc.ServerStreamingServer[ExecStreamResponse]

func _ForkDaemon_Terminate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TerminateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ForkDaemonServer).Terminate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ForkDaemon_Terminate_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ForkDaemonServer).Terminate(ctx, req.(*TerminateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ForkDaemon_ReadFile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReadFileRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ForkDaemonServer).ReadFile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ForkDaemon_ReadFile_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ForkDaemonServer).ReadFile(ctx, req.(*ReadFileRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ForkDaemon_WriteFile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(WriteFileRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ForkDaemonServer).WriteFile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ForkDaemon_WriteFile_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ForkDaemonServer).WriteFile(ctx, req.(*WriteFileRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ForkDaemon_ListDir_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListDirRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ForkDaemonServer).ListDir(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ForkDaemon_ListDir_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ForkDaemonServer).ListDir(ctx, req.(*ListDirRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ForkDaemon_GetCapacity_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetCapacityRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ForkDaemonServer).GetCapacity(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ForkDaemon_GetCapacity_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ForkDaemonServer).GetCapacity(ctx, req.(*GetCapacityRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ForkDaemon_ServiceDesc is the grpc.ServiceDesc for ForkDaemon service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ForkDaemon_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "forkd.ForkDaemon",
	HandlerType: (*ForkDaemonServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateTemplate",
			Handler:    _ForkDaemon_CreateTemplate_Handler,
		},
		{
			MethodName: "DeleteTemplate",
			Handler:    _ForkDaemon_DeleteTemplate_Handler,
		},
		{
			MethodName: "ListTemplates",
			Handler:    _ForkDaemon_ListTemplates_Handler,
		},
		{
			MethodName: "CreateSnapshot",
			Handler:    _ForkDaemon_CreateSnapshot_Handler,
		},
		{
			MethodName: "DeleteSnapshot",
			Handler:    _ForkDaemon_DeleteSnapshot_Handler,
		},
		{
			MethodName: "Fork",
			Handler:    _ForkDaemon_Fork_Handler,
		},
		{
			MethodName: "ForkRunning",
			Handler:    _ForkDaemon_ForkRunning_Handler,
		},
		{
			MethodName: "Exec",
			Handler:    _ForkDaemon_Exec_Handler,
		},
		{
			MethodName: "Terminate",
			Handler:    _ForkDaemon_Terminate_Handler,
		},
		{
			MethodName: "ReadFile",
			Handler:    _ForkDaemon_ReadFile_Handler,
		},
		{
			MethodName: "WriteFile",
			Handler:    _ForkDaemon_WriteFile_Handler,
		},
		{
			MethodName: "ListDir",
			Handler:    _ForkDaemon_ListDir_Handler,
		},
		{
			MethodName: "GetCapacity",
			Handler:    _ForkDaemon_GetCapacity_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "ExecStream",
			Handler:       _ForkDaemon_ExecStream_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "proto/forkd.proto",
}
