// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.0
// source: proto/forkd.proto

package forkdpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ExecStreamResponse_Stream int32

const (
	ExecStreamResponse_STDOUT ExecStreamResponse_Stream = 0
	ExecStreamResponse_STDERR ExecStreamResponse_Stream = 1
)

// Enum value maps for ExecStreamResponse_Stream.
var (
	ExecStreamResponse_Stream_name = map[int32]string{
		0: "STDOUT",
		1: "STDERR",
	}
	ExecStreamResponse_Stream_value = map[string]int32{
		"STDOUT": 0,
		"STDERR": 1,
	}
)

func (x ExecStreamResponse_Stream) Enum() *ExecStreamResponse_Stream {
	p := new(ExecStreamResponse_Stream)
	*p = x
	return p
}

func (x ExecStreamResponse_Stream) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ExecStreamResponse_Stream) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_forkd_proto_enumTypes[0].Descriptor()
}

func (ExecStreamResponse_Stream) Type() protoreflect.EnumType {
	return &file_proto_forkd_proto_enumTypes[0]
}

func (x ExecStreamResponse_Stream) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ExecStreamResponse_Stream.Descriptor instead.
func (ExecStreamResponse_Stream) EnumDescriptor() ([]byte, []int) {
	return file_proto_forkd_proto_rawDescGZIP(), []int{19, 0}
}

type CreateTemplateRequest struct {
	state        protoimpl.MessageState `protogen:"open.v1"`
	TemplateId   string                 `protobuf:"bytes,1,opt,name=template_id,json=templateId,proto3" json:"template_id,omitempty"`
	Image        string                 `protobuf:"bytes,2,opt,name=image,proto3" json:"image,omitempty"`
	InitCommands []string               `protobuf:"bytes,3,rep,name=init_commands,json=initCommands,proto3" json:"init_commands,omitempty"`
	KernelPath   string                 `protobuf:"bytes,4,opt,name=kernel_path,json=kernelPath,proto3" json:"kernel_path,omitempty"`
	Resources    *ResourceSpec          `protobuf:"bytes,5,opt,name=resources,proto3" json:"resources,omitempty"`
	// Volumes the template declares. The node bakes one placeholder block device
	// per volume into the snapshot at build time so each fork can rebind it to
	// its own backing; the fork's ForkRequest.volumes must match this set by
	// name. Empty means the template has no volumes.
	Volumes       []*VolumeMount `protobuf:"bytes,6,rep,name=volumes,proto3" json:"volumes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateTemplateRequest) Reset() {
	*x = CreateTemplateRequest{}
	mi := &file_proto_forkd_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateTemplateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateTemplateRequest) ProtoMessage() {}

func (x *CreateTemplateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_forkd_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateTemplateRequest.ProtoReflect.Descriptor instead.
func (*CreateTemplateRequest) Descriptor() ([]byte, []int) {
	return file_proto_forkd_proto_rawDescGZIP(), []int{0}
}

func (x *CreateTemplateRequest) GetTemplateId() string {
	if x != nil {
		return x.TemplateId
	}
	return ""
}

func (x *CreateTemplateRequest) GetImage() string {
	if x != nil {
		return x.Image
	}
	return ""
}

func (x *CreateTemplateRequest) GetInitCommands() []string {
	if x != nil {
		return x.InitCommands
	}
	return nil
}

func (x *CreateTemplateRequest) GetKernelPath() string {
	if x != nil {
		return x.KernelPath
	}
	return ""
}

func (x *CreateTemplateRequest) GetResources() *ResourceSpec {
	if x != nil {
		return x.Resources
	}
	return nil
}

func (x *CreateTemplateRequest) GetVolumes() []*VolumeMount {
	if x != nil {
		return x.Volumes
	}
	return nil
}

type CreateTemplateResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	TemplateId     string                 `protobuf:"bytes,1,opt,name=template_id,json=templateId,proto3" json:"template_id,omitempty"`
	CreationTimeMs float64                `protobuf:"fixed64,2,opt,name=creation_time_ms,json=creationTimeMs,proto3" json:"creation_time_ms,omitempty"`
	// Content-addressed manifest digest of the snapshot just built. A stable
	// identifier for the snapshot, safe to log; the controller records it in the
	// SandboxPool status.
	TemplateDigest string `protobuf:"bytes,3,opt,name=template_digest,json=templateDigest,proto3" json:"template_digest,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *CreateTemplateResponse) Reset() {
	*x = CreateTemplateResponse{}
	mi := &file_proto_forkd_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateTemplateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateTemplateResponse) ProtoMessage() {}

func (x *CreateTemplateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_forkd_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateTemplateResponse.ProtoReflect.Descriptor instead.
func (*CreateTemplateResponse) Descriptor() ([]byte, []int) {
	return file_proto_forkd_proto_rawDescGZIP(), []int{1}
}

func (x *CreateTemplateResponse) GetTemplateId() string {
	if x != nil {
		return x.TemplateId
	}
	return ""
}

func (x *CreateTemplateResponse) GetCreationTimeMs() float64 {
	if x != nil {
		return x.CreationTimeMs
	}
	return 0
}

func (x *CreateTemplateResponse) GetTemplateDigest() string {
	if x != nil {
		return x.TemplateDigest
	}
	return ""
}

type DeleteTemplateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TemplateId    string                 `protobuf:"bytes,1,opt,name=template_id,json=templateId,proto3" json:"template_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteTemplateRequest) Reset() {
	*x = DeleteTemplateRequest{}
	mi := &file_proto_forkd_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteTemplateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteTemplateRequest) ProtoMessage() {}

func (x *DeleteTemplateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_forkd_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteTemplateRequest.ProtoReflect.Descriptor instead.
func (*DeleteTemplateRequest) Descriptor() ([]byte, []int) {
	return file_proto_forkd_proto_rawDescGZIP(), []int{2}
}

func (x *DeleteTemplateRequest) GetTemplateId() string {
	if x != nil {
		return x.TemplateId
	}
	return ""
}

type DeleteTemplateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteTemplateResponse) Reset() {
	*x = DeleteTemplateResponse{}
	mi := &file_proto_forkd_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteTemplateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteTemplateResponse) ProtoMessage() {}

func (x *DeleteTemplateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_forkd_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteTemplateResponse.ProtoReflect.Descriptor instead.
func (*DeleteTemplateResponse) Descriptor() ([]byte, []int) {
	return file_proto_forkd_proto_rawDescGZIP(), []int{3}
}

type ListTemplatesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListTemplatesRequest) Reset() {
	*x = ListTemplatesRequest{}
	mi := &file_proto_forkd_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListTemplatesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTemplatesRequest) ProtoMessage() {}

func (x *ListTemplatesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_forkd_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTemplatesRequest.ProtoReflect.Descriptor instead.
func (*ListTemplatesRequest) Descriptor() ([]byte, []int) {
	return file_proto_forkd_proto_rawDescGZIP(), []int{4}
}

type ListTemplatesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Templates     []*TemplateInfo        `protobuf:"bytes,1,rep,name=templates,proto3" json:"templates,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListTemplatesResponse) Reset() {
	*x = ListTemplatesResponse{}
	mi := &file_proto_forkd_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListTemplatesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTemplatesResponse) ProtoMessage() {}

func (x *ListTemplatesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_forkd_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTemplatesResponse.ProtoReflect.Descriptor instead.
func (*ListTemplatesResponse) Descriptor() ([]byte, []int) {
	return file_proto_forkd_proto_rawDescGZIP(), []int{5}
}

func (x *ListTemplatesResponse) GetTemplates() []*TemplateInfo {
	if x != nil {
		return x.Templates
	}
	return nil
}

type TemplateInfo struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	TemplateId        string                 `protobuf:"bytes,1,opt,name=template_id,json=templateId,proto3" json:"template_id,omitempty"`
	Image             string                 `protobuf:"bytes,2,opt,name=image,proto3" json:"image,omitempty"`
	SnapshotSizeBytes int64                  `protobuf:"varint,3,opt,name=snapshot_size_bytes,json=snapshotSizeBytes,proto3" json:"snapshot_size_bytes,omitempty"`
	CreatedAtUnix     int64                  `protobuf:"varint,4,opt,name=created_at_unix,json=createdAtUnix,proto3" json:"created_at_unix,omitempty"`
	Ready             bool                   `protobuf:"varint,5,opt,name=ready,proto3" json:"ready,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *TemplateInfo) Reset() {
	*x = TemplateInfo{}
	mi := &file_proto_forkd_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TemplateInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TemplateInfo) ProtoMessage() {}

func (x *TemplateInfo) ProtoReflect() protoreflect.Message {
	mi := &file_proto_forkd_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TemplateInfo.ProtoReflect.Descriptor instead.
func (*TemplateInfo) Descriptor() ([]byte, []int) {
	return file_proto_forkd_proto_rawDescGZIP(), []int{6}
}

func (x *TemplateInfo) GetTemplateId() string {
	if x != nil {
		return x.TemplateId
	}
	return ""
}

func (x *TemplateInfo) GetImage() string {
	if x != nil {
		return x.Image
	}
	return ""
}

func (x *TemplateInfo) GetSnapshotSizeBytes() int64 {
	if x != nil {
		return x.SnapshotSizeBytes
	}
	return 0
}

func (x *TemplateInfo) GetCreatedAtUnix() int64 {
	if x != nil {
		return x.CreatedAtUnix
	}
	return 0
}

func (x *TemplateInfo) GetReady() bool {
	if x != nil {
		return x.Ready
	}
	return false
}

type CreateSnapshotRequest struct {
	state      protoimpl.MessageState `protogen:"open.v1"`
	TemplateId string                 `protobuf:"bytes,1,opt,name=template_id,json=templateId,proto3" json:"template_id,omitempty"`
	SnapshotId string                 `protobuf:"bytes,2,opt,name=snapshot_id,json=snapshotId,proto3" json:"snapshot_id,omitempty"`
	// Wait for this condition before snapshotting
	WaitCondition string `protobuf:"bytes,3,opt,name=wait_condition,json=waitCondition,proto3" json:"wait_condition,omitempty"`
	// Delay after condition is met
	DelaySeconds  int32 `protobuf:"varint,4,opt,name=delay_seconds,json=delaySeconds,proto3" json:"delay_seconds,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateSnapshotRequest) Reset() {
	*x = CreateSnapshotRequest{}
	mi := &file_proto_forkd_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateSnapshotRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateSnapshotRequest) ProtoMessage() {}

func (x *CreateSnapshotRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_forkd_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateSnapshotRequest.ProtoReflect.Descriptor instead.
func (*CreateSnapshotRequest) Descriptor() ([]byte, []int) {
	return file_proto_forkd_proto_rawDescGZIP(), []int{7}
}

func (x *CreateSnapshotRequest) GetTemplateId() string {
	if x != nil {
		return x.TemplateId
	}
	return ""
}

func (x *CreateSnapshotRequest) GetSnapshotId() string {
	if x != nil {
		return x.SnapshotId
	}
	return ""
}

func (x *CreateSnapshotRequest) GetWaitCondition() string {
	if x != nil {
		return x.WaitCondition
	}
	return ""
}

func (x *CreateSnapshotRequest) GetDelaySeconds() int32 {
	if x != nil {
		return x.DelaySeconds
	}
	return 0
}

type CreateSnapshotResponse struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	SnapshotId        string                 `protobuf:"bytes,1,opt,name=snapshot_id,json=snapshotId,proto3" json:"snapshot_id,omitempty"`
	SnapshotTimeMs    float64                `protobuf:"fixed64,2,opt,name=snapshot_time_ms,json=snapshotTimeMs,proto3" json:"snapshot_time_ms,omitempty"`
	SnapshotSizeBytes int64                  `protobuf:"varint,3,opt,name=snapshot_size_bytes,json=snapshotSizeBytes,proto3" json:"snapshot_size_bytes,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *CreateSnapshotResponse) Reset() {
	*x = CreateSnapshotResponse{}
	mi := &file_proto_forkd_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateSnapshotResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateSnapshotResponse) ProtoMessage() {}

func (x *CreateSnapshotResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_forkd_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateSnapshotResponse.ProtoReflect.Descriptor instead.
func (*CreateSnapshotResponse) Descriptor() ([]byte, []int) {
	return file_proto_forkd_proto_rawDescGZIP(), []int{8}
}

func (x *CreateSnapshotResponse) GetSnapshotId() string {
	if x != nil {
		return x.SnapshotId
	}
	return ""
}

func (x *CreateSnapshotResponse) GetSnapshotTimeMs() float64 {
	if x != nil {
		return x.SnapshotTimeMs
	}
	return 0
}

func (x *CreateSnapshotResponse) GetSnapshotSizeBytes() int64 {
	if x != nil {
		return x.SnapshotSizeBytes
	}
	return 0
}

type DeleteSnapshotRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SnapshotId    string                 `protobuf:"bytes,1,opt,name=snapshot_id,json=snapshotId,proto3" json:"snapshot_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteSnapshotRequest) Reset() {
	*x = DeleteSnapshotRequest{}
	mi := &file_proto_forkd_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteSnapshotRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteSnapshotRequest) ProtoMessage() {}

func (x *DeleteSnapshotRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_forkd_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteSnapshotRequest.ProtoReflect.Descriptor instead.
func (*DeleteSnapshotRequest) Descriptor() ([]byte, []int) {
	return file_proto_forkd_proto_rawDescGZIP(), []int{9}
}

func (x *DeleteSnapshotRequest) GetSnapshotId() string {
	if x != nil {
		return x.SnapshotId
	}
	return ""
}

type DeleteSnapshotResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteSnapshotResponse) Reset() {
	*x = DeleteSnapshotResponse{}
	mi := &file_proto_forkd_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteSnapshotResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteSnapshotResponse) ProtoMessage() {}

func (x *DeleteSnapshotResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_forkd_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteSnapshotResponse.ProtoReflect.Descriptor instead.
func (*DeleteSnapshotResponse) Descriptor() ([]byte, []int) {
	return file_proto_forkd_proto_rawDescGZIP(), []int{10}
}

type ForkRequest struct {
	state      protoimpl.MessageState `protogen:"open.v1"`
	SnapshotId string                 `protobuf:"bytes,1,opt,name=snapshot_id,json=snapshotId,proto3" json:"snapshot_id,omitempty"`
	SandboxId  string                 `protobuf:"bytes,2,opt,name=sandbox_id,json=sandboxId,proto3" json:"sandbox_id,omitempty"`
	Env        []*EnvVar              `protobuf:"bytes,3,rep,name=env,proto3" json:"env,omitempty"`
	Secrets    []*SecretVar           `protobuf:"bytes,4,rep,name=secrets,proto3" json:"secrets,omitempty"`
	Network    *NetworkConfig         `protobuf:"bytes,5,opt,name=network,proto3" json:"network,omitempty"`
	// Bearer token the HTTP sandbox API will require for this sandbox.
	// Empty means no token is registered and HTTP calls fail closed (401).
	ApiToken string `protobuf:"bytes,6,opt,name=api_token,json=apiToken,proto3" json:"api_token,omitempty"`
	// Volumes to prepare and attach to the fork. The node resolves the backing
	// source for Snapshot/Share/Clone policies; the controller passes the policy
	// and spec.
	Volumes       []*VolumeMount `protobuf:"bytes,7,rep,name=volumes,proto3" json:"volumes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ForkRequest) Reset() {
	*x = ForkRequest{}
	mi := &file_proto_forkd_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ForkRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ForkRequest) ProtoMessage() {}

func (x *ForkRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_forkd_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ForkRequest.ProtoReflect.Descriptor instead.
func (*ForkRequest) Descriptor() ([]byte, []int) {
	return file_proto_forkd_proto_rawDescGZIP(), []int{11}
}

func (x *ForkRequest) GetSnapshotId() string {
	if x != nil {
		return x.SnapshotId
	}
	return ""
}

func (x *ForkRequest) GetSandboxId() string {
	if x != nil {
		return x.SandboxId
	}
	return ""
}

func (x *ForkRequest) GetEnv() []*EnvVar {
	if x != nil {
		return x.Env
	}
	return nil
}

func (x *ForkRequest) GetSecrets() []*SecretVar {
	if x != nil {
		return x.Secrets
	}
	return nil
}

func (x *ForkRequest) GetNetwork() *NetworkConfig {
	if x != nil {
		return x.Network
	}
	return nil
}

func (x *ForkRequest) GetApiToken() string {
	if x != nil {
		return x.ApiToken
	}
	return ""
}

func (x *ForkRequest) GetVolumes() []*VolumeMount {
	if x != nil {
		return x.Volumes
	}
	return nil
}

type VolumeMount struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	Name      string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	MountPath string                 `protobuf:"bytes,2,opt,name=mount_path,json=mountPath,proto3" json:"mount_path,omitempty"`
	ReadOnly  bool                   `protobuf:"varint,3,opt,name=read_only,json=readOnly,proto3" json:"read_only,omitempty"`
	// fork_policy is the API ForkPolicy string: Fresh, Share, Clone, Snapshot.
	ForkPolicy string `protobuf:"bytes,4,opt,name=fork_policy,json=forkPolicy,proto3" json:"fork_policy,omitempty"`
	// size is a Kubernetes resource quantity such as 5Gi or 512Mi. Empty uses the
	// node default. Only meaningful for the Fresh policy.
	Size          string `protobuf:"bytes,5,opt,name=size,proto3" json:"size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VolumeMount) Reset() {
	*x = VolumeMount{}
	mi := &file_proto_forkd_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VolumeMount) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VolumeMount) ProtoMessage() {}

func (x *VolumeMount) ProtoReflect() protoreflect.Message {
	mi := &file_proto_forkd_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VolumeMount.ProtoReflect.Descriptor instead.
func (*VolumeMount) Descriptor() ([]byte, []int) {
	return file_proto_forkd_proto_rawDescGZIP(), []int{12}
}

func (x *VolumeMount) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *VolumeMount) GetMountPath() string {
	if x != nil {
		return x.MountPath
	}
	return ""
}

func (x *VolumeMount) GetReadOnly() bool {
	if x != nil {
		return x.ReadOnly
	}
	return false
}

func (x *VolumeMount) GetForkPolicy() string {
	if x != nil {
		return x.ForkPolicy
	}
	return ""
}

func (x *VolumeMount) GetSize() string {
	if x != nil {
		return x.Size
	}
	return ""
}

type ForkResponse struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	SandboxId         string                 `protobuf:"bytes,1,opt,name=sandbox_id,json=sandboxId,proto3" json:"sandbox_id,omitempty"`
	Endpoint          string                 `protobuf:"bytes,2,opt,name=endpoint,proto3" json:"endpoint,omitempty"`
	ForkTimeMs        float64                `protobuf:"fixed64,3,opt,name=fork_time_ms,json=forkTimeMs,proto3" json:"fork_time_ms,omitempty"`
	MemoryUniqueBytes int64                  `protobuf:"varint,4,opt,name=memory_unique_bytes,json=memoryUniqueBytes,proto3" json:"memory_unique_bytes,omitempty"`
	MemorySharedBytes int64                  `protobuf:"varint,5,opt,name=memory_shared_bytes,json=memorySharedBytes,proto3" json:"memory_shared_bytes,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *ForkResponse) Reset() {
	*x = ForkResponse{}
	mi := &file_proto_forkd_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ForkResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ForkResponse) ProtoMessage() {}

func (x *ForkResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_forkd_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ForkResponse.ProtoReflect.Descriptor instead.
func (*ForkResponse) Descriptor() ([]byte, []int) {
	return file_proto_forkd_proto_rawDescGZIP(), []int{13}
}

func (x *ForkResponse) GetSandboxId() string {
	if x != nil {
		return x.SandboxId
	}
	return ""
}

func (x *ForkResponse) GetEndpoint() string {
	if x != nil {
		return x.Endpoint
	}
	return ""
}

func (x *ForkResponse) GetForkTimeMs() float64 {
	if x != nil {
		return x.ForkTimeMs
	}
	return 0
}

func (x *ForkResponse) GetMemoryUniqueBytes() int64 {
	if x != nil {
		return x.MemoryUniqueBytes
	}
	return 0
}

func (x *ForkResponse) GetMemorySharedBytes() int64 {
	if x != nil {
		return x.MemorySharedBytes
	}
	return 0
}

type ForkRunningRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	SourceSandboxId string                 `protobuf:"bytes,1,opt,name=source_sandbox_id,json=sourceSandboxId,proto3" json:"source_sandbox_id,omitempty"`
	NewSandboxId    string                 `protobuf:"bytes,2,opt,name=new_sandbox_id,json=newSandboxId,proto3" json:"new_sandbox_id,omitempty"`
	PauseSource     bool                   `protobuf:"varint,3,opt,name=pause_source,json=pauseSource,proto3" json:"pause_source,omitempty"`
	Env             []*EnvVar              `protobuf:"bytes,4,rep,name=env,proto3" json:"env,omitempty"`
	// Bearer token the HTTP sandbox API will require for the new sandbox.
	// Empty means no token is registered and HTTP calls fail closed (401).
	ApiToken      string `protobuf:"bytes,5,opt,name=api_token,json=apiToken,proto3" json:"api_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ForkRunningRequest) Reset() {
	*x = ForkRunningRequest{}
	mi := &file_proto_forkd_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ForkRunningRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ForkRunningRequest) ProtoMessage() {}

func (x *ForkRunningRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_forkd_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ForkRunningRequest.ProtoReflect.Descriptor instead.
func (*ForkRunningRequest) Descriptor() ([]byte, []int) {
	return file_proto_forkd_proto_rawDescGZIP(), []int{14}
}

func (x *ForkRunningRequest) GetSourceSandboxId() string {
	if x != nil {
		return x.SourceSandboxId
	}
	return ""
}

func (x *ForkRunningRequest) GetNewSandboxId() string {
	if x != nil {
		return x.NewSandboxId
	}
	return ""
}

func (x *ForkRunningRequest) GetPauseSource() bool {
	if x != nil {
		return x.PauseSource
	}
	return false
}

func (x *ForkRunningRequest) GetEnv() []*EnvVar {
	if x != nil {
		return x.Env
	}
	return nil
}

func (x *ForkRunningRequest) GetApiToken() string {
	if x != nil {
		return x.ApiToken
	}
	return ""
}

type ForkRunningResponse struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	SandboxId        string                 `protobuf:"bytes,1,opt,name=sandbox_id,json=sandboxId,proto3" json:"sandbox_id,omitempty"`
	Endpoint         string                 `protobuf:"bytes,2,opt,name=endpoint,proto3" json:"endpoint,omitempty"`
	CheckpointTimeMs float64                `protobuf:"fixed64,3,opt,name=checkpoint_time_ms,json=checkpointTimeMs,proto3" json:"checkpoint_time_ms,omitempty"`
	ForkTimeMs       float64                `protobuf:"fixed64,4,opt,name=fork_time_ms,json=forkTimeMs,proto3" json:"fork_time_ms,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *ForkRunningResponse) Reset() {
	*x = ForkRunningResponse{}
	mi := &file_proto_forkd_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ForkRunningResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ForkRunningResponse) ProtoMessage() {}

func (x *ForkRunningResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_forkd_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ForkRunningResponse.ProtoReflect.Descriptor instead.
func (*ForkRunningResponse) Descriptor() ([]byte, []int) {
	return file_proto_forkd_proto_rawDescGZIP(), []int{15}
}

func (x *ForkRunningResponse) GetSandboxId() string {
	if x != nil {
		return x.SandboxId
	}
	return ""
}

func (x *ForkRunningResponse) GetEndpoint() string {
	if x != nil {
		return x.Endpoint
	}
	return ""
}

func (x *ForkRunningResponse) GetCheckpointTimeMs() float64 {
	if x != nil {
		return x.CheckpointTimeMs
	}
	return 0
}

func (x *ForkRunningResponse) GetForkTimeMs() float64 {
	if x != nil {
		return x.ForkTimeMs
	}
	return 0
}

type ExecRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	SandboxId      string                 `protobuf:"bytes,1,opt,name=sandbox_id,json=sandboxId,proto3" json:"sandbox_id,omitempty"`
	Command        string                 `protobuf:"bytes,2,opt,name=command,proto3" json:"command,omitempty"`
	TimeoutSeconds int32                  `protobuf:"varint,3,opt,name=timeout_seconds,json=timeoutSeconds,proto3" json:"timeout_seconds,omitempty"`
	WorkingDir     string                 `protobuf:"bytes,4,opt,name=working_dir,json=workingDir,proto3" json:"working_dir,omitempty"`
	Env            []*EnvVar              `protobuf:"bytes,5,rep,name=env,proto3" json:"env,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ExecRequest) Reset() {
	*x = ExecRequest{}
	mi := &file_proto_forkd_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecRequest) ProtoMessage() {}

func (x *ExecRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_forkd_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecRequest.ProtoReflect.Descriptor instead.
func (*ExecRequest) Descriptor() ([]byte, []int) {
	return file_proto_forkd_proto_rawDescGZIP(), []int{16}
}

func (x *ExecRequest) GetSandboxId() string {
	if x != nil {
		return x.SandboxId
	}
	return ""
}

func (x *ExecRequest) GetCommand() string {
	if x != nil {
		return x.Command
	}
	return ""
}

func (x *ExecRequest) GetTimeoutSeconds() int32 {
	if x != nil {
		return x.TimeoutSeconds
	}
	return 0
}

func (x *ExecRequest) GetWorkingDir() string {
	if x != nil {
		return x.WorkingDir
	}
	return ""
}

func (x *ExecRequest) GetEnv() []*EnvVar {
	if x != nil {
		return x.Env
	}
	return nil
}

type ExecResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ExitCode      int32                  `protobuf:"varint,1,opt,name=exit_code,json=exitCode,proto3" json:"exit_code,omitempty"`
	Stdout        string                 `protobuf:"bytes,2,opt,name=stdout,proto3" json:"stdout,omitempty"`
	Stderr        string                 `protobuf:"bytes,3,opt,name=stderr,proto3" json:"stderr,omitempty"`
	ExecTimeMs    float64                `protobuf:"fixed64,4,opt,name=exec_time_ms,json=execTimeMs,proto3" json:"exec_time_ms,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecResponse) Reset() {
	*x = ExecResponse{}
	mi := &file_proto_forkd_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecResponse) ProtoMessage() {}

func (x *ExecResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_forkd_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecResponse.ProtoReflect.Descriptor instead.
func (*ExecResponse) Descriptor() ([]byte, []int) {
	return file_proto_forkd_proto_rawDescGZIP(), []int{17}
}

func (x *ExecResponse) GetExitCode() int32 {
	if x != nil {
		return x.ExitCode
	}
	return 0
}

func (x *ExecResponse) GetStdout() string {
	if x != nil {
		return x.Stdout
	}
	return ""
}

func (x *ExecResponse) GetStderr() string {
	if x != nil {
		return x.Stderr
	}
	return ""
}

func (x *ExecResponse) GetExecTimeMs() float64 {
	if x != nil {
		return x.ExecTimeMs
	}
	return 0
}

type ExecStreamRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	SandboxId      string                 `protobuf:"bytes,1,opt,name=sandbox_id,json=sandboxId,proto3" json:"sandbox_id,omitempty"`
	Command        string                 `protobuf:"bytes,2,opt,name=command,proto3" json:"command,omitempty"`
	TimeoutSeconds int32                  `protobuf:"varint,3,opt,name=timeout_seconds,json=timeoutSeconds,proto3" json:"timeout_seconds,omitempty"`
	WorkingDir     string                 `protobuf:"bytes,4,opt,name=working_dir,json=workingDir,proto3" json:"working_dir,omitempty"`
	Env            []*EnvVar              `protobuf:"bytes,5,rep,name=env,proto3" json:"env,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ExecStreamRequest) Reset() {
	*x = ExecStreamRequest{}
	mi := &file_proto_forkd_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecStreamRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecStreamRequest) ProtoMessage() {}

func (x *ExecStreamRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_forkd_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecStreamRequest.ProtoReflect.Descriptor instead.
func (*ExecStreamRequest) Descriptor() ([]byte, []int) {
	return file_proto_forkd_proto_rawDescGZIP(), []int{18}
}

func (x *ExecStreamRequest) GetSandboxId() string {
	if x != nil {
		return x.SandboxId
	}
	return ""
}

func (x *ExecStreamRequest) GetCommand() string {
	if x != nil {
		return x.Command
	}
	return ""
}

func (x *ExecStreamRequest) GetTimeoutSeconds() int32 {
	if x != nil {
		return x.TimeoutSeconds
	}
	return 0
}

func (x *ExecStreamRequest) GetWorkingDir() string {
	if x != nil {
		return x.WorkingDir
	}
	return ""
}

func (x *ExecStreamRequest) GetEnv() []*EnvVar {
	if x != nil {
		return x.Env
	}
	return nil
}

type ExecStreamResponse struct {
	state  protoimpl.MessageState    `protogen:"open.v1"`
	Stream ExecStreamResponse_Stream `protobuf:"varint,1,opt,name=stream,proto3,enum=forkd.ExecStreamResponse_Stream" json:"stream,omitempty"`
	Data   []byte                    `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	// Set on the final message
	Done          bool  `protobuf:"varint,3,opt,name=done,proto3" json:"done,omitempty"`
	ExitCode      int32 `protobuf:"varint,4,opt,name=exit_code,json=exitCode,proto3" json:"exit_code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecStreamResponse) Reset() {
	*x = ExecStreamResponse{}
	mi := &file_proto_forkd_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecStreamResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecStreamResponse) ProtoMessage() {}

func (x *ExecStreamResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_forkd_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecStreamResponse.ProtoReflect.Descriptor instead.
func (*ExecStreamResponse) Descriptor() ([]byte, []int) {
	return file_proto_forkd_proto_rawDescGZIP(), []int{19}
}

func (x *ExecStreamResponse) GetStream() ExecStreamResponse_Stream {
	if x != nil {
		return x.Stream
	}
	return ExecStreamResponse_STDOUT
}

func (x *ExecStreamResponse) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *ExecStreamResponse) GetDone() bool {
	if x != nil {
		return x.Done
	}
	return false
}

func (x *ExecStreamResponse) GetExitCode() int32 {
	if x != nil {
		return x.ExitCode
	}
	return 0
}

type TerminateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SandboxId     string                 `protobuf:"bytes,1,opt,name=sandbox_id,json=sandboxId,proto3" json:"sandbox_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TerminateRequest) Reset() {
	*x = TerminateRequest{}
	mi := &file_proto_forkd_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TerminateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TerminateRequest) ProtoMessage() {}

func (x *TerminateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_forkd_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TerminateRequest.ProtoReflect.Descriptor instead.
func (*TerminateRequest) Descriptor() ([]byte, []int) {
	return file_proto_forkd_proto_rawDescGZIP(), []int{20}
}

func (x *TerminateRequest) GetSandboxId() string {
	if x != nil {
		return x.SandboxId
	}
	return ""
}

type TerminateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UptimeSeconds float64                `protobuf:"fixed64,1,opt,name=uptime_seconds,json=uptimeSeconds,proto3" json:"uptime_seconds,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TerminateResponse) Reset() {
	*x = TerminateResponse{}
	mi := &file_proto_forkd_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TerminateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TerminateResponse) ProtoMessage() {}

func (x *TerminateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_forkd_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TerminateResponse.ProtoReflect.Descriptor instead.
func (*TerminateResponse) Descriptor() ([]byte, []int) {
	return file_proto_forkd_proto_rawDescGZIP(), []int{21}
}

func (x *TerminateResponse) GetUptimeSeconds() float64 {
	if x != nil {
		return x.UptimeSeconds
	}
	return 0
}

type ListSandboxesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListSandboxesRequest) Reset() {
	*x = ListSandboxesRequest{}
	mi := &file_proto_forkd_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListSandboxesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListSandboxesRequest) ProtoMessage() {}

func (x *ListSandboxesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_forkd_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListSandboxesRequest.ProtoReflect.Descriptor instead.
func (*ListSandboxesRequest) Descriptor() ([]byte, []int) {
	return file_proto_forkd_proto_rawDescGZIP(), []int{22}
}

type ListSandboxesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Sandboxes     []*SandboxInfo         `protobuf:"bytes,1,rep,name=sandboxes,proto3" json:"sandboxes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListSandboxesResponse) Reset() {
	*x = ListSandboxesResponse{}
	mi := &file_proto_forkd_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListSandboxesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListSandboxesResponse) ProtoMessage() {}

func (x *ListSandboxesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_forkd_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListSandboxesResponse.ProtoReflect.Descriptor instead.
func (*ListSandboxesResponse) Descriptor() ([]byte, []int) {
	return file_proto_forkd_proto_rawDescGZIP(), []int{23}
}

func (x *ListSandboxesResponse) GetSandboxes() []*SandboxInfo {
	if x != nil {
		return x.Sandboxes
	}
	return nil
}

type SandboxInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SandboxId     string                 `protobuf:"bytes,1,opt,name=sandbox_id,json=sandboxId,proto3" json:"sandbox_id,omitempty"`
	CreatedAtUnix int64                  `protobuf:"varint,2,opt,name=created_at_unix,json=createdAtUnix,proto3" json:"created_at_unix,omitempty"`
	// zero when never accessed
	LastActivityUnix int64 `protobuf:"varint,3,opt,name=last_activity_unix,json=lastActivityUnix,proto3" json:"last_activity_unix,omitempty"`
	UptimeSeconds    int64 `protobuf:"varint,4,opt,name=uptime_seconds,json=uptimeSeconds,proto3" json:"uptime_seconds,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *SandboxInfo) Reset() {
	*x = SandboxInfo{}
	mi := &file_proto_forkd_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SandboxInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SandboxInfo) ProtoMessage() {}

func (x *SandboxInfo) ProtoReflect() protoreflect.Message {
	mi := &file_proto_forkd_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SandboxInfo.ProtoReflect.Descriptor instead.
func (*SandboxInfo) Descriptor() ([]byte, []int) {
	return file_proto_forkd_proto_rawDescGZIP(), []int{24}
}

func (x *SandboxInfo) GetSandboxId() string {
	if x != nil {
		return x.SandboxId
	}
	return ""
}

func (x *SandboxInfo) GetCreatedAtUnix() int64 {
	if x != nil {
		return x.CreatedAtUnix
	}
	return 0
}

func (x *SandboxInfo) GetLastActivityUnix() int64 {
	if x != nil {
		return x.LastActivityUnix
	}
	return 0
}

func (x *SandboxInfo) GetUptimeSeconds() int64 {
	if x != nil {
		return x.UptimeSeconds
	}
	return 0
}

type ReadFileRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SandboxId     string                 `protobuf:"bytes,1,opt,name=sandbox_id,json=sandboxId,proto3" json:"sandbox_id,omitempty"`
	Path          string                 `protobuf:"bytes,2,opt,name=path,proto3" json:"path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReadFileRequest) Reset() {
	*x = ReadFileRequest{}
	mi := &file_proto_forkd_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadFileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadFileRequest) ProtoMessage() {}

func (x *ReadFileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_forkd_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadFileRequest.ProtoReflect.Descriptor instead.
func (*ReadFileRequest) Descriptor() ([]byte, []int) {
	return file_proto_forkd_proto_rawDescGZIP(), []int{25}
}

func (x *ReadFileRequest) GetSandboxId() string {
	if x != nil {
		return x.SandboxId
	}
	return ""
}

func (x *ReadFileRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

type ReadFileResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Content       []byte                 `protobuf:"bytes,1,opt,name=content,proto3" json:"content,omitempty"`
	Size          int64                  `protobuf:"varint,2,opt,name=size,proto3" json:"size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReadFileResponse) Reset() {
	*x = ReadFileResponse{}
	mi := &file_proto_forkd_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadFileResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadFileResponse) ProtoMessage() {}

func (x *ReadFileResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_forkd_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadFileResponse.ProtoReflect.Descriptor instead.
func (*ReadFileResponse) Descriptor() ([]byte, []int) {
	return file_proto_forkd_proto_rawDescGZIP(), []int{26}
}

func (x *ReadFileResponse) GetContent() []byte {
	if x != nil {
		return x.Content
	}
	return nil
}

func (x *ReadFileResponse) GetSize() int64 {
	if x != nil {
		return x.Size
	}
	return 0
}

type WriteFileRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SandboxId     string                 `protobuf:"bytes,1,opt,name=sandbox_id,json=sandboxId,proto3" json:"sandbox_id,omitempty"`
	Path          string                 `protobuf:"bytes,2,opt,name=path,proto3" json:"path,omitempty"`
	Content       []byte                 `protobuf:"bytes,3,opt,name=content,proto3" json:"content,omitempty"`
	Mode          uint32                 `protobuf:"varint,4,opt,name=mode,proto3" json:"mode,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WriteFileRequest) Reset() {
	*x = WriteFileRequest{}
	mi := &file_proto_forkd_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WriteFileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WriteFileRequest) ProtoMessage() {}

func (x *WriteFileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_forkd_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WriteFileRequest.ProtoReflect.Descriptor instead.
func (*WriteFileRequest) Descriptor() ([]byte, []int) {
	return file_proto_forkd_proto_rawDescGZIP(), []int{27}
}

func (x *WriteFileRequest) GetSandboxId() string {
	if x != nil {
		return x.SandboxId
	}
	return ""
}

func (x *WriteFileRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *WriteFileRequest) GetContent() []byte {
	if x != nil {
		return x.Content
	}
	return nil
}

func (x *WriteFileRequest) GetMode() uint32 {
	if x != nil {
		return x.Mode
	}
	return 0
}

type WriteFileResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WriteFileResponse) Reset() {
	*x = WriteFileResponse{}
	mi := &file_proto_forkd_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WriteFileResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WriteFileResponse) ProtoMessage() {}

func (x *WriteFileResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_forkd_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WriteFileResponse.ProtoReflect.Descriptor instead.
func (*WriteFileResponse) Descriptor() ([]byte, []int) {
	return file_proto_forkd_proto_rawDescGZIP(), []int{28}
}

type ListDirRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SandboxId     string                 `protobuf:"bytes,1,opt,name=sandbox_id,json=sandboxId,proto3" json:"sandbox_id,omitempty"`
	Path          string                 `protobuf:"bytes,2,opt,name=path,proto3" json:"path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListDirRequest) Reset() {
	*x = ListDirRequest{}
	mi := &file_proto_forkd_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListDirRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListDirRequest) ProtoMessage() {}

func (x *ListDirRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_forkd_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListDirRequest.ProtoReflect.Descriptor instead.
func (*ListDirRequest) Descriptor() ([]byte, []int) {
	return file_proto_forkd_proto_rawDescGZIP(), []int{29}
}

func (x *ListDirRequest) GetSandboxId() string {
	if x != nil {
		return x.SandboxId
	}
	return ""
}

func (x *ListDirRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

type ListDirResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Entries       []*FileInfo            `protobuf:"bytes,1,rep,name=entries,proto3" json:"entries,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListDirResponse) Reset() {
	*x = ListDirResponse{}
	mi := &file_proto_forkd_proto_msgTypes[30]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListDirResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListDirResponse) ProtoMessage() {}

func (x *ListDirResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_forkd_proto_msgTypes[30]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListDirResponse.ProtoReflect.Descriptor instead.
func (*ListDirResponse) Descriptor() ([]byte, []int) {
	return file_proto_forkd_proto_rawDescGZIP(), []int{30}
}

func (x *ListDirResponse) GetEntries() []*FileInfo {
	if x != nil {
		return x.Entries
	}
	return nil
}

type FileInfo struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Name           string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	IsDir          bool                   `protobuf:"varint,2,opt,name=is_dir,json=isDir,proto3" json:"is_dir,omitempty"`
	Size           int64                  `protobuf:"varint,3,opt,name=size,proto3" json:"size,omitempty"`
	ModifiedAtUnix int64                  `protobuf:"varint,4,opt,name=modified_at_unix,json=modifiedAtUnix,proto3" json:"modified_at_unix,omitempty"`
	Mode           uint32                 `protobuf:"varint,5,opt,name=mode,proto3" json:"mode,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *FileInfo) Reset() {
	*x = FileInfo{}
	mi := &file_proto_forkd_proto_msgTypes[31]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FileInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileInfo) ProtoMessage() {}

func (x *FileInfo) ProtoReflect() protoreflect.Message {
	mi := &file_proto_forkd_proto_msgTypes[31]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileInfo.ProtoReflect.Descriptor instead.
func (*FileInfo) Descriptor() ([]byte, []int) {
	return file_proto_forkd_proto_rawDescGZIP(), []int{31}
}

func (x *FileInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *FileInfo) GetIsDir() bool {
	if x != nil {
		return x.IsDir
	}
	return false
}

func (x *FileInfo) GetSize() int64 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *FileInfo) GetModifiedAtUnix() int64 {
	if x != nil {
		return x.ModifiedAtUnix
	}
	return 0
}

func (x *FileInfo) GetMode() uint32 {
	if x != nil {
		return x.Mode
	}
	return 0
}

type GetCapacityRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCapacityRequest) Reset() {
	*x = GetCapacityRequest{}
	mi := &file_proto_forkd_proto_msgTypes[32]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCapacityRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCapacityRequest) ProtoMessage() {}

func (x *GetCapacityRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_forkd_proto_msgTypes[32]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCapacityRequest.ProtoReflect.Descriptor instead.
func (*GetCapacityRequest) Descriptor() ([]byte, []int) {
	return file_proto_forkd_proto_rawDescGZIP(), []int{32}
}

type GetCapacityResponse struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	ActiveSandboxes   int32                  `protobuf:"varint,1,opt,name=active_sandboxes,json=activeSandboxes,proto3" json:"active_sandboxes,omitempty"`
	MaxSandboxes      int32                  `protobuf:"varint,2,opt,name=max_sandboxes,json=maxSandboxes,proto3" json:"max_sandboxes,omitempty"`
	MemoryTotalBytes  int64                  `protobuf:"varint,3,opt,name=memory_total_bytes,json=memoryTotalBytes,proto3" json:"memory_total_bytes,omitempty"`
	MemoryUsedBytes   int64                  `protobuf:"varint,4,opt,name=memory_used_bytes,json=memoryUsedBytes,proto3" json:"memory_used_bytes,omitempty"`
	MemorySharedBytes int64                  `protobuf:"varint,5,opt,name=memory_shared_bytes,json=memorySharedBytes,proto3" json:"memory_shared_bytes,omitempty"`
	TemplateIds       []string               `protobuf:"bytes,6,rep,name=template_ids,json=templateIds,proto3" json:"template_ids,omitempty"`
	SnapshotIds       []string               `protobuf:"bytes,7,rep,name=snapshot_ids,json=snapshotIds,proto3" json:"snapshot_ids,omitempty"`
	KvmAvailable      bool                   `protobuf:"varint,8,opt,name=kvm_available,json=kvmAvailable,proto3" json:"kvm_available,omitempty"`
	// template_digests maps each template id to its content-addressed snapshot
	// manifest digest (safe to log). Lets the controller record the snapshot
	// identity in the SandboxPool status even for templates it did not just
	// build.
	TemplateDigests map[string]string `protobuf:"bytes,9,rep,name=template_digests,json=templateDigests,proto3" json:"template_digests,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *GetCapacityResponse) Reset() {
	*x = GetCapacityResponse{}
	mi := &file_proto_forkd_proto_msgTypes[33]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCapacityResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCapacityResponse) ProtoMessage() {}

func (x *GetCapacityResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_forkd_proto_msgTypes[33]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCapacityResponse.ProtoReflect.Descriptor instead.
func (*GetCapacityResponse) Descriptor() ([]byte, []int) {
	return file_proto_forkd_proto_rawDescGZIP(), []int{33}
}

func (x *GetCapacityResponse) GetActiveSandboxes() int32 {
	if x != nil {
		return x.ActiveSandboxes
	}
	return 0
}

func (x *GetCapacityResponse) GetMaxSandboxes() int32 {
	if x != nil {
		return x.MaxSandboxes
	}
	return 0
}

func (x *GetCapacityResponse) GetMemoryTotalBytes() int64 {
	if x != nil {
		return x.MemoryTotalBytes
	}
	return 0
}

func (x *GetCapacityResponse) GetMemoryUsedBytes() int64 {
	if x != nil {
		return x.MemoryUsedBytes
	}
	return 0
}

func (x *GetCapacityResponse) GetMemorySharedBytes() int64 {
	if x != nil {
		return x.MemorySharedBytes
	}
	return 0
}

func (x *GetCapacityResponse) GetTemplateIds() []string {
	if x != nil {
		return x.TemplateIds
	}
	return nil
}

func (x *GetCapacityResponse) GetSnapshotIds() []string {
	if x != nil {
		return x.SnapshotIds
	}
	return nil
}

func (x *GetCapacityResponse) GetKvmAvailable() bool {
	if x != nil {
		return x.KvmAvailable
	}
	return false
}

func (x *GetCapacityResponse) GetTemplateDigests() map[string]string {
	if x != nil {
		return x.TemplateDigests
	}
	return nil
}

type ResourceSpec struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Vcpus         int32                  `protobuf:"varint,1,opt,name=vcpus,proto3" json:"vcpus,omitempty"`
	MemoryMb      int64                  `protobuf:"varint,2,opt,name=memory_mb,json=memoryMb,proto3" json:"memory_mb,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResourceSpec) Reset() {
	*x = ResourceSpec{}
	mi := &file_proto_forkd_proto_msgTypes[34]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResourceSpec) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResourceSpec) ProtoMessage() {}

func (x *ResourceSpec) ProtoReflect() protoreflect.Message {
	mi := &file_proto_forkd_proto_msgTypes[34]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResourceSpec.ProtoReflect.Descriptor instead.
func (*ResourceSpec) Descriptor() ([]byte, []int) {
	return file_proto_forkd_proto_rawDescGZIP(), []int{34}
}

func (x *ResourceSpec) GetVcpus() int32 {
	if x != nil {
		return x.Vcpus
	}
	return 0
}

func (x *ResourceSpec) GetMemoryMb() int64 {
	if x != nil {
		return x.MemoryMb
	}
	return 0
}

type EnvVar struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value         string                 `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EnvVar) Reset() {
	*x = EnvVar{}
	mi := &file_proto_forkd_proto_msgTypes[35]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EnvVar) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnvVar) ProtoMessage() {}

func (x *EnvVar) ProtoReflect() protoreflect.Message {
	mi := &file_proto_forkd_proto_msgTypes[35]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnvVar.ProtoReflect.Descriptor instead.
func (*EnvVar) Descriptor() ([]byte, []int) {
	return file_proto_forkd_proto_rawDescGZIP(), []int{35}
}

func (x *EnvVar) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *EnvVar) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

type SecretVar struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value         string                 `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SecretVar) Reset() {
	*x = SecretVar{}
	mi := &file_proto_forkd_proto_msgTypes[36]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SecretVar) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SecretVar) ProtoMessage() {}

func (x *SecretVar) ProtoReflect() protoreflect.Message {
	mi := &file_proto_forkd_proto_msgTypes[36]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SecretVar.ProtoReflect.Descriptor instead.
func (*SecretVar) Descriptor() ([]byte, []int) {
	return file_proto_forkd_proto_rawDescGZIP(), []int{36}
}

func (x *SecretVar) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *SecretVar) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

type NetworkConfig struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EgressPolicy  string                 `protobuf:"bytes,1,opt,name=egress_policy,json=egressPolicy,proto3" json:"egress_policy,omitempty"`
	AllowList     []string               `protobuf:"bytes,2,rep,name=allow_list,json=allowList,proto3" json:"allow_list,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NetworkConfig) Reset() {
	*x = NetworkConfig{}
	mi := &file_proto_forkd_proto_msgTypes[37]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NetworkConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NetworkConfig) ProtoMessage() {}

func (x *NetworkConfig) ProtoReflect() protoreflect.Message {
	mi := &file_proto_forkd_proto_msgTypes[37]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NetworkConfig.ProtoReflect.Descriptor instead.
func (*NetworkConfig) Descriptor() ([]byte, []int) {
	return file_proto_forkd_proto_rawDescGZIP(), []int{37}
}

func (x *NetworkConfig) GetEgressPolicy() string {
	if x != nil {
		return x.EgressPolicy
	}
	return ""
}

func (x *NetworkConfig) GetAllowList() []string {
	if x != nil {
		return x.AllowList
	}
	return nil
}

var File_proto_forkd_proto protoreflect.FileDescriptor

const file_proto_forkd_proto_rawDesc = "" +
	"\n" +
	"\x11proto/forkd.proto\x12\x05forkd\"\xf5\x01\n" +
	"\x15CreateTemplateRequest\x12\x1f\n" +
	"\vtemplate_id\x18\x01 \x01(\tR\n" +
	"templateId\x12\x14\n" +
	"\x05image\x18\x02 \x01(\tR\x05image\x12#\n" +
	"\rinit_commands\x18\x03 \x03(\tR\finitCommands\x12\x1f\n" +
	"\vkernel_path\x18\x04 \x01(\tR\n" +
	"kernelPath\x121\n" +
	"\tresources\x18\x05 \x01(\v2\x13.forkd.ResourceSpecR\tresources\x12,\n" +
	"\avolumes\x18\x06 \x03(\v2\x12.forkd.VolumeMountR\avolumes\"\x8c\x01\n" +
	"\x16CreateTemplateResponse\x12\x1f\n" +
	"\vtemplate_id\x18\x01 \x01(\tR\n" +
	"templateId\x12(\n" +
	"\x10creation_time_ms\x18\x02 \x01(\x01R\x0ecreationTimeMs\x12'\n" +
	"\x0ftemplate_digest\x18\x03 \x01(\tR\x0etemplateDigest\"8\n" +
	"\x15DeleteTemplateRequest\x12\x1f\n" +
	"\vtemplate_id\x18\x01 \x01(\tR\n" +
	"templateId\"\x18\n" +
	"\x16DeleteTemplateResponse\"\x16\n" +
	"\x14ListTemplatesRequest\"J\n" +
	"\x15ListTemplatesResponse\x121\n" +
	"\ttemplates\x18\x01 \x03(\v2\x13.forkd.TemplateInfoR\ttemplates\"\xb3\x01\n" +
	"\fTemplateInfo\x12\x1f\n" +
	"\vtemplate_id\x18\x01 \x01(\tR\n" +
	"templateId\x12\x14\n" +
	"\x05image\x18\x02 \x01(\tR\x05image\x12.\n" +
	"\x13snapshot_size_bytes\x18\x03 \x01(\x03R\x11snapshotSizeBytes\x12&\n" +
	"\x0fcreated_at_unix\x18\x04 \x01(\x03R\rcreatedAtUnix\x12\x14\n" +
	"\x05ready\x18\x05 \x01(\bR\x05ready\"\xa5\x01\n" +
	"\x15CreateSnapshotRequest\x12\x1f\n" +
	"\vtemplate_id\x18\x01 \x01(\tR\n" +
	"templateId\x12\x1f\n" +
	"\vsnapshot_id\x18\x02 \x01(\tR\n" +
	"snapshotId\x12%\n" +
	"\x0ewait_condition\x18\x03 \x01(\tR\rwaitCondition\x12#\n" +
	"\rdelay_seconds\x18\x04 \x01(\x05R\fdelaySeconds\"\x93\x01\n" +
	"\x16CreateSnapshotResponse\x12\x1f\n" +
	"\vsnapshot_id\x18\x01 \x01(\tR\n" +
	"snapshotId\x12(\n" +
	"\x10snapshot_time_ms\x18\x02 \x01(\x01R\x0esnapshotTimeMs\x12.\n" +
	"\x13snapshot_size_bytes\x18\x03 \x01(\x03R\x11snapshotSizeBytes\"8\n" +
	"\x15DeleteSnapshotRequest\x12\x1f\n" +
	"\vsnapshot_id\x18\x01 \x01(\tR\n" +
	"snapshotId\"\x18\n" +
	"\x16DeleteSnapshotResponse\"\x95\x02\n" +
	"\vForkRequest\x12\x1f\n" +
	"\vsnapshot_id\x18\x01 \x01(\tR\n" +
	"snapshotId\x12\x1d\n" +
	"\n" +
	"sandbox_id\x18\x02 \x01(\tR\tsandboxId\x12\x1f\n" +
	"\x03env\x18\x03 \x03(\v2\r.forkd.EnvVarR\x03env\x12*\n" +
	"\asecrets\x18\x04 \x03(\v2\x10.forkd.SecretVarR\asecrets\x12.\n" +
	"\anetwork\x18\x05 \x01(\v2\x14.forkd.NetworkConfigR\anetwork\x12\x1b\n" +
	"\tapi_token\x18\x06 \x01(\tR\bapiToken\x12,\n" +
	"\avolumes\x18\a \x03(\v2\x12.forkd.VolumeMountR\avolumes\"\x92\x01\n" +
	"\vVolumeMount\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1d\n" +
	"\n" +
	"mount_path\x18\x02 \x01(\tR\tmountPath\x12\x1b\n" +
	"\tread_only\x18\x03 \x01(\bR\breadOnly\x12\x1f\n" +
	"\vfork_policy\x18\x04 \x01(\tR\n" +
	"forkPolicy\x12\x12\n" +
	"\x04size\x18\x05 \x01(\tR\x04size\"\xcb\x01\n" +
	"\fForkResponse\x12\x1d\n" +
	"\n" +
	"sandbox_id\x18\x01 \x01(\tR\tsandboxId\x12\x1a\n" +
	"\bendpoint\x18\x02 \x01(\tR\bendpoint\x12 \n" +
	"\ffork_time_ms\x18\x03 \x01(\x01R\n" +
	"forkTimeMs\x12.\n" +
	"\x13memory_unique_bytes\x18\x04 \x01(\x03R\x11memoryUniqueBytes\x12.\n" +
	"\x13memory_shared_bytes\x18\x05 \x01(\x03R\x11memorySharedBytes\"\xc7\x01\n" +
	"\x12ForkRunningRequest\x12*\n" +
	"\x11source_sandbox_id\x18\x01 \x01(\tR\x0fsourceSandboxId\x12$\n" +
	"\x0enew_sandbox_id\x18\x02 \x01(\tR\fnewSandboxId\x12!\n" +
	"\fpause_source\x18\x03 \x01(\bR\vpauseSource\x12\x1f\n" +
	"\x03env\x18\x04 \x03(\v2\r.forkd.EnvVarR\x03env\x12\x1b\n" +
	"\tapi_token\x18\x05 \x01(\tR\bapiToken\"\xa0\x01\n" +
	"\x13ForkRunningResponse\x12\x1d\n" +
	"\n" +
	"sandbox_id\x18\x01 \x01(\tR\tsandboxId\x12\x1a\n" +
	"\bendpoint\x18\x02 \x01(\tR\bendpoint\x12,\n" +
	"\x12checkpoint_time_ms\x18\x03 \x01(\x01R\x10checkpointTimeMs\x12 \n" +
	"\ffork_time_ms\x18\x04 \x01(\x01R\n" +
	"forkTimeMs\"\xb1\x01\n" +
	"\vExecRequest\x12\x1d\n" +
	"\n" +
	"sandbox_id\x18\x01 \x01(\tR\tsandboxId\x12\x18\n" +
	"\acommand\x18\x02 \x01(\tR\acommand\x12'\n" +
	"\x0ftimeout_seconds\x18\x03 \x01(\x05R\x0etimeoutSeconds\x12\x1f\n" +
	"\vworking_dir\x18\x04 \x01(\tR\n" +
	"workingDir\x12\x1f\n" +
	"\x03env\x18\x05 \x03(\v2\r.forkd.EnvVarR\x03env\"}\n" +
	"\fExecResponse\x12\x1b\n" +
	"\texit_code\x18\x01 \x01(\x05R\bexitCode\x12\x16\n" +
	"\x06stdout\x18\x02 \x01(\tR\x06stdout\x12\x16\n" +
	"\x06stderr\x18\x03 \x01(\tR\x06stderr\x12 \n" +
	"\fexec_time_ms\x18\x04 \x01(\x01R\n" +
	"execTimeMs\"\xb7\x01\n" +
	"\x11ExecStreamRequest\x12\x1d\n" +
	"\n" +
	"sandbox_id\x18\x01 \x01(\tR\tsandboxId\x12\x18\n" +
	"\acommand\x18\x02 \x01(\tR\acommand\x12'\n" +
	"\x0ftimeout_seconds\x18\x03 \x01(\x05R\x0etimeoutSeconds\x12\x1f\n" +
	"\vworking_dir\x18\x04 \x01(\tR\n" +
	"workingDir\x12\x1f\n" +
	"\x03env\x18\x05 \x03(\v2\r.forkd.EnvVarR\x03env\"\xb5\x01\n" +
	"\x12ExecStreamResponse\x128\n" +
	"\x06stream\x18\x01 \x01(\x0e2 .forkd.ExecStreamResponse.StreamR\x06stream\x12\x12\n" +
	"\x04data\x18\x02 \x01(\fR\x04data\x12\x12\n" +
	"\x04done\x18\x03 \x01(\bR\x04done\x12\x1b\n" +
	"\texit_code\x18\x04 \x01(\x05R\bexitCode\" \n" +
	"\x06Stream\x12\n" +
	"\n" +
	"\x06STDOUT\x10\x00\x12\n" +
	"\n" +
	"\x06STDERR\x10\x01\"1\n" +
	"\x10TerminateRequest\x12\x1d\n" +
	"\n" +
	"sandbox_id\x18\x01 \x01(\tR\tsandboxId\":\n" +
	"\x11TerminateResponse\x12%\n" +
	"\x0euptime_seconds\x18\x01 \x01(\x01R\ruptimeSeconds\"\x16\n" +
	"\x14ListSandboxesRequest\"I\n" +
	"\x15ListSandboxesResponse\x120\n" +
	"\tsandboxes\x18\x01 \x03(\v2\x12.forkd.SandboxInfoR\tsandboxes\"\xa9\x01\n" +
	"\vSandboxInfo\x12\x1d\n" +
	"\n" +
	"sandbox_id\x18\x01 \x01(\tR\tsandboxId\x12&\n" +
	"\x0fcreated_at_unix\x18\x02 \x01(\x03R\rcreatedAtUnix\x12,\n" +
	"\x12last_activity_unix\x18\x03 \x01(\x03R\x10lastActivityUnix\x12%\n" +
	"\x0euptime_seconds\x18\x04 \x01(\x03R\ruptimeSeconds\"D\n" +
	"\x0fReadFileRequest\x12\x1d\n" +
	"\n" +
	"sandbox_id\x18\x01 \x01(\tR\tsandboxId\x12\x12\n" +
	"\x04path\x18\x02 \x01(\tR\x04path\"@\n" +
	"\x10ReadFileResponse\x12\x18\n" +
	"\acontent\x18\x01 \x01(\fR\acontent\x12\x12\n" +
	"\x04size\x18\x02 \x01(\x03R\x04size\"s\n" +
	"\x10WriteFileRequest\x12\x1d\n" +
	"\n" +
	"sandbox_id\x18\x01 \x01(\tR\tsandboxId\x12\x12\n" +
	"\x04path\x18\x02 \x01(\tR\x04path\x12\x18\n" +
	"\acontent\x18\x03 \x01(\fR\acontent\x12\x12\n" +
	"\x04mode\x18\x04 \x01(\rR\x04mode\"\x13\n" +
	"\x11WriteFileResponse\"C\n" +
	"\x0eListDirRequest\x12\x1d\n" +
	"\n" +
	"sandbox_id\x18\x01 \x01(\tR\tsandboxId\x12\x12\n" +
	"\x04path\x18\x02 \x01(\tR\x04path\"<\n" +
	"\x0fListDirResponse\x12)\n" +
	"\aentries\x18\x01 \x03(\v2\x0f.forkd.FileInfoR\aentries\"\x87\x01\n" +
	"\bFileInfo\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x15\n" +
	"\x06is_dir\x18\x02 \x01(\bR\x05isDir\x12\x12\n" +
	"\x04size\x18\x03 \x01(\x03R\x04size\x12(\n" +
	"\x10modified_at_unix\x18\x04 \x01(\x03R\x0emodifiedAtUnix\x12\x12\n" +
	"\x04mode\x18\x05 \x01(\rR\x04mode\"\x14\n" +
	"\x12GetCapacityRequest\"\xfa\x03\n" +
	"\x13GetCapacityResponse\x12)\n" +
	"\x10active_sandboxes\x18\x01 \x01(\x05R\x0factiveSandboxes\x12#\n" +
	"\rmax_sandboxes\x18\x02 \x01(\x05R\fmaxSandboxes\x12,\n" +
	"\x12memory_total_bytes\x18\x03 \x01(\x03R\x10memoryTotalBytes\x12*\n" +
	"\x11memory_used_bytes\x18\x04 \x01(\x03R\x0fmemoryUsedBytes\x12.\n" +
	"\x13memory_shared_bytes\x18\x05 \x01(\x03R\x11memorySharedBytes\x12!\n" +
	"\ftemplate_ids\x18\x06 \x03(\tR\vtemplateIds\x12!\n" +
	"\fsnapshot_ids\x18\a \x03(\tR\vsnapshotIds\x12#\n" +
	"\rkvm_available\x18\b \x01(\bR\fkvmAvailable\x12Z\n" +
	"\x10template_digests\x18\t \x03(\v2/.forkd.GetCapacityResponse.TemplateDigestsEntryR\x0ftemplateDigests\x1aB\n" +
	"\x14TemplateDigestsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"A\n" +
	"\fResourceSpec\x12\x14\n" +
	"\x05vcpus\x18\x01 \x01(\x05R\x05vcpus\x12\x1b\n" +
	"\tmemory_mb\x18\x02 \x01(\x03R\bmemoryMb\"0\n" +
	"\x06EnvVar\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value\"3\n" +
	"\tSecretVar\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value\"S\n" +
	"\rNetworkConfig\x12#\n" +
	"\regress_policy\x18\x01 \x01(\tR\fegressPolicy\x12\x1d\n" +
	"\n" +
	"allow_list\x18\x02 \x03(\tR\tallowList2\x8a\b\n" +
	"\n" +
	"ForkDaemon\x12M\n" +
	"\x0eCreateTemplate\x12\x1c.forkd.CreateTemplateRequest\x1a\x1d.forkd.CreateTemplateResponse\x12M\n" +
	"\x0eDeleteTemplate\x12\x1c.forkd.DeleteTemplateRequest\x1a\x1d.forkd.DeleteTemplateResponse\x12J\n" +
	"\rListTemplates\x12\x1b.forkd.ListTemplatesRequest\x1a\x1c.forkd.ListTemplatesResponse\x12M\n" +
	"\x0eCreateSnapshot\x12\x1c.forkd.CreateSnapshotRequest\x1a\x1d.forkd.CreateSnapshotResponse\x12M\n" +
	"\x0eDeleteSnapshot\x12\x1c.forkd.DeleteSnapshotRequest\x1a\x1d.forkd.DeleteSnapshotResponse\x12/\n" +
	"\x04Fork\x12\x12.forkd.ForkRequest\x1a\x13.forkd.ForkResponse\x12D\n" +
	"\vForkRunning\x12\x19.forkd.ForkRunningRequest\x1a\x1a.forkd.ForkRunningResponse\x12/\n" +
	"\x04Exec\x12\x12.forkd.ExecRequest\x1a\x13.forkd.ExecResponse\x12C\n" +
	"\n" +
	"ExecStream\x12\x18.forkd.ExecStreamRequest\x1a\x19.forkd.ExecStreamResponse0\x01\x12>\n" +
	"\tTerminate\x12\x17.forkd.TerminateRequest\x1a\x18.forkd.TerminateResponse\x12J\n" +
	"\rListSandboxes\x12\x1b.forkd.ListSandboxesRequest\x1a\x1c.forkd.ListSandboxesResponse\x12;\n" +
	"\bReadFile\x12\x16.forkd.ReadFileRequest\x1a\x17.forkd.ReadFileResponse\x12>\n" +
	"\tWriteFile\x12\x17.forkd.WriteFileRequest\x1a\x18.forkd.WriteFileResponse\x128\n" +
	"\aListDir\x12\x15.forkd.ListDirRequest\x1a\x16.forkd.ListDirResponse\x12D\n" +
	"\vGetCapacity\x12\x19.forkd.GetCapacityRequest\x1a\x1a.forkd.GetCapacityResponseB5Z3github.com/paperclipinc/sandbox/proto/forkd;forkdpbb\x06proto3"

var (
	file_proto_forkd_proto_rawDescOnce sync.Once
	file_proto_forkd_proto_rawDescData []byte
)

func file_proto_forkd_proto_rawDescGZIP() []byte {
	file_proto_forkd_proto_rawDescOnce.Do(func() {
		file_proto_forkd_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_forkd_proto_rawDesc), len(file_proto_forkd_proto_rawDesc)))
	})
	return file_proto_forkd_proto_rawDescData
}

var file_proto_forkd_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_proto_forkd_proto_msgTypes = make([]protoimpl.MessageInfo, 39)
var file_proto_forkd_proto_goTypes = []any{
	(ExecStreamResponse_Stream)(0), // 0: forkd.ExecStreamResponse.Stream
	(*CreateTemplateRequest)(nil),  // 1: forkd.CreateTemplateRequest
	(*CreateTemplateResponse)(nil), // 2: forkd.CreateTemplateResponse
	(*DeleteTemplateRequest)(nil),  // 3: forkd.DeleteTemplateRequest
	(*DeleteTemplateResponse)(nil), // 4: forkd.DeleteTemplateResponse
	(*ListTemplatesRequest)(nil),   // 5: forkd.ListTemplatesRequest
	(*ListTemplatesResponse)(nil),  // 6: forkd.ListTemplatesResponse
	(*TemplateInfo)(nil),           // 7: forkd.TemplateInfo
	(*CreateSnapshotRequest)(nil),  // 8: forkd.CreateSnapshotRequest
	(*CreateSnapshotResponse)(nil), // 9: forkd.CreateSnapshotResponse
	(*DeleteSnapshotRequest)(nil),  // 10: forkd.DeleteSnapshotRequest
	(*DeleteSnapshotResponse)(nil), // 11: forkd.DeleteSnapshotResponse
	(*ForkRequest)(nil),            // 12: forkd.ForkRequest
	(*VolumeMount)(nil),            // 13: forkd.VolumeMount
	(*ForkResponse)(nil),           // 14: forkd.ForkResponse
	(*ForkRunningRequest)(nil),     // 15: forkd.ForkRunningRequest
	(*ForkRunningResponse)(nil),    // 16: forkd.ForkRunningResponse
	(*ExecRequest)(nil),            // 17: forkd.ExecRequest
	(*ExecResponse)(nil),           // 18: forkd.ExecResponse
	(*ExecStreamRequest)(nil),      // 19: forkd.ExecStreamRequest
	(*ExecStreamResponse)(nil),     // 20: forkd.ExecStreamResponse
	(*TerminateRequest)(nil),       // 21: forkd.TerminateRequest
	(*TerminateResponse)(nil),      // 22: forkd.TerminateResponse
	(*ListSandboxesRequest)(nil),   // 23: forkd.ListSandboxesRequest
	(*ListSandboxesResponse)(nil),  // 24: forkd.ListSandboxesResponse
	(*SandboxInfo)(nil),            // 25: forkd.SandboxInfo
	(*ReadFileRequest)(nil),        // 26: forkd.ReadFileRequest
	(*ReadFileResponse)(nil),       // 27: forkd.ReadFileResponse
	(*WriteFileRequest)(nil),       // 28: forkd.WriteFileRequest
	(*WriteFileResponse)(nil),      // 29: forkd.WriteFileResponse
	(*ListDirRequest)(nil),         // 30: forkd.ListDirRequest
	(*ListDirResponse)(nil),        // 31: forkd.ListDirResponse
	(*FileInfo)(nil),               // 32: forkd.FileInfo
	(*GetCapacityRequest)(nil),     // 33: forkd.GetCapacityRequest
	(*GetCapacityResponse)(nil),    // 34: forkd.GetCapacityResponse
	(*ResourceSpec)(nil),           // 35: forkd.ResourceSpec
	(*EnvVar)(nil),                 // 36: forkd.EnvVar
	(*SecretVar)(nil),              // 37: forkd.SecretVar
	(*NetworkConfig)(nil),          // 38: forkd.NetworkConfig
	nil,                            // 39: forkd.GetCapacityResponse.TemplateDigestsEntry
}
var file_proto_forkd_proto_depIdxs = []int32{
	35, // 0: forkd.CreateTemplateRequest.resources:type_name -> forkd.ResourceSpec
	13, // 1: forkd.CreateTemplateRequest.volumes:type_name -> forkd.VolumeMount
	7,  // 2: forkd.ListTemplatesResponse.templates:type_name -> forkd.TemplateInfo
	36, // 3: forkd.ForkRequest.env:type_name -> forkd.EnvVar
	37, // 4: forkd.ForkRequest.secrets:type_name -> forkd.SecretVar
	38, // 5: forkd.ForkRequest.network:type_name -> forkd.NetworkConfig
	13, // 6: forkd.ForkRequest.volumes:type_name -> forkd.VolumeMount
	36, // 7: forkd.ForkRunningRequest.env:type_name -> forkd.EnvVar
	36, // 8: forkd.ExecRequest.env:type_name -> forkd.EnvVar
	36, // 9: forkd.ExecStreamRequest.env:type_name -> forkd.EnvVar
	0,  // 10: forkd.ExecStreamResponse.stream:type_name -> forkd.ExecStreamResponse.Stream
	25, // 11: forkd.ListSandboxesResponse.sandboxes:type_name -> forkd.SandboxInfo
	32, // 12: forkd.ListDirResponse.entries:type_name -> forkd.FileInfo
	39, // 13: forkd.GetCapacityResponse.template_digests:type_name -> forkd.GetCapacityResponse.TemplateDigestsEntry
	1,  // 14: forkd.ForkDaemon.CreateTemplate:input_type -> forkd.CreateTemplateRequest
	3,  // 15: forkd.ForkDaemon.DeleteTemplate:input_type -> forkd.DeleteTemplateRequest
	5,  // 16: forkd.ForkDaemon.ListTemplates:input_type -> forkd.ListTemplatesRequest
	8,  // 17: forkd.ForkDaemon.CreateSnapshot:input_type -> forkd.CreateSnapshotRequest
	10, // 18: forkd.ForkDaemon.DeleteSnapshot:input_type -> forkd.DeleteSnapshotRequest
	12, // 19: forkd.ForkDaemon.Fork:input_type -> forkd.ForkRequest
	15, // 20: forkd.ForkDaemon.ForkRunning:input_type -> forkd.ForkRunningRequest
	17, // 21: forkd.ForkDaemon.Exec:input_type -> forkd.ExecRequest
	19, // 22: forkd.ForkDaemon.ExecStream:input_type -> forkd.ExecStreamRequest
	21, // 23: forkd.ForkDaemon.Terminate:input_type -> forkd.TerminateRequest
	23, // 24: forkd.ForkDaemon.ListSandboxes:input_type -> forkd.ListSandboxesRequest
	26, // 25: forkd.ForkDaemon.ReadFile:input_type -> forkd.ReadFileRequest
	28, // 26: forkd.ForkDaemon.WriteFile:input_type -> forkd.WriteFileRequest
	30, // 27: forkd.ForkDaemon.ListDir:input_type -> forkd.ListDirRequest
	33, // 28: forkd.ForkDaemon.GetCapacity:input_type -> forkd.GetCapacityRequest
	2,  // 29: forkd.ForkDaemon.CreateTemplate:output_type -> forkd.CreateTemplateResponse
	4,  // 30: forkd.ForkDaemon.DeleteTemplate:output_type -> forkd.DeleteTemplateResponse
	6,  // 31: forkd.ForkDaemon.ListTemplates:output_type -> forkd.ListTemplatesResponse
	9,  // 32: forkd.ForkDaemon.CreateSnapshot:output_type -> forkd.CreateSnapshotResponse
	11, // 33: forkd.ForkDaemon.DeleteSnapshot:output_type -> forkd.DeleteSnapshotResponse
	14, // 34: forkd.ForkDaemon.Fork:output_type -> forkd.ForkResponse
	16, // 35: forkd.ForkDaemon.ForkRunning:output_type -> forkd.ForkRunningResponse
	18, // 36: forkd.ForkDaemon.Exec:output_type -> forkd.ExecResponse
	20, // 37: forkd.ForkDaemon.ExecStream:output_type -> forkd.ExecStreamResponse
	22, // 38: forkd.ForkDaemon.Terminate:output_type -> forkd.TerminateResponse
	24, // 39: forkd.ForkDaemon.ListSandboxes:output_type -> forkd.ListSandboxesResponse
	27, // 40: forkd.ForkDaemon.ReadFile:output_type -> forkd.ReadFileResponse
	29, // 41: forkd.ForkDaemon.WriteFile:output_type -> forkd.WriteFileResponse
	31, // 42: forkd.ForkDaemon.ListDir:output_type -> forkd.ListDirResponse
	34, // 43: forkd.ForkDaemon.GetCapacity:output_type -> forkd.GetCapacityResponse
	29, // [29:44] is the sub-list for method output_type
	14, // [14:29] is the sub-list for method input_type
	14, // [14:14] is the sub-list for extension type_name
	14, // [14:14] is the sub-list for extension extendee
	0,  // [0:14] is the sub-list for field type_name
}

func init() { file_proto_forkd_proto_init() }
func file_proto_forkd_proto_init() {
	if File_proto_forkd_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_forkd_proto_rawDesc), len(file_proto_forkd_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   39,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_forkd_proto_goTypes,
		DependencyIndexes: file_proto_forkd_proto_depIdxs,
		EnumInfos:         file_proto_forkd_proto_enumTypes,
		MessageInfos:      file_proto_forkd_proto_msgTypes,
	}.Build()
	File_proto_forkd_proto = out.File
	file_proto_forkd_proto_goTypes = nil
	file_proto_forkd_proto_depIdxs = nil
}
